[build]
builder = "nixpacks"
buildCommand = "npm run build && npx prisma db push"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
