[build]
builder = "nixpacks"
buildCommand = "sh scripts/build.sh"

[deploy]
startCommand = "sh scripts/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
